/*
 * Copyright 2026 SorrowBlue. See LICENSE for details.
 */

package com.sorrowblue.comicviewer.framework.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.Modifier

class NavKeyProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        processNavKeys(resolver)
        processNavigationEntries(resolver)
        return emptyList()
    }

    private fun processNavKeys(resolver: Resolver) {
        val symbols = resolver.getSymbolsWithAnnotation("kotlinx.serialization.Serializable")
        
        val navKeys = symbols
            .filterIsInstance<KSClassDeclaration>()
            .filter { it.implementsNavKey() }
            .toList()

        if (navKeys.isEmpty()) return

        val firstKey = navKeys.first()
        val keyPackage = firstKey.packageName.asString()
        val diPackage = if (keyPackage.endsWith(".navigation")) {
            keyPackage.substringBeforeLast(".navigation") + ".di"
        } else if (keyPackage.endsWith(".navigation3")) {
            keyPackage.substringBeforeLast(".navigation3") + ".di"
        } else {
            "$keyPackage.di"
        }

        val prefix = "com.sorrowblue.comicviewer."
        val moduleName = if (keyPackage.startsWith(prefix)) {
            keyPackage.removePrefix(prefix)
                .replace(".", "_")
                .split("_")
                .filter { it != "navigation" && it != "navigation3" && it != "feature" && it != "di" }
                .joinToString("") { it.replaceFirstChar(Char::titlecase) }
        } else {
            keyPackage.replace(".", "_")
                .split("_")
                .joinToString("") { it.replaceFirstChar(Char::titlecase) }
        }

        val className = "Generated${moduleName}NavKeyModule"
        val methodName = "provide${moduleName}NavKeySubclassMap"

        val fileSpec = buildString {
            appendLine("/*")
            appendLine(" * Generated by NavKeyProcessor. Do not modify.")
            appendLine(" */")
            appendLine()
            appendLine("package $diPackage")
            appendLine()
            navKeys.forEach { key ->
                appendLine("import ${key.qualifiedName?.asString()}")
            }
            appendLine("import androidx.navigation3.runtime.NavKey")
            appendLine("import com.sorrowblue.comicviewer.framework.ui.navigation3.NavKeyEntry")
            appendLine("import dev.zacsweers.metro.AppScope")
            appendLine("import dev.zacsweers.metro.ContributesTo")
            appendLine("import dev.zacsweers.metro.ElementsIntoSet")
            appendLine("import dev.zacsweers.metro.Provides")
            appendLine("import kotlin.reflect.KClass")
            appendLine("import kotlinx.serialization.KSerializer")
            appendLine()
            appendLine("@ContributesTo(AppScope::class)")
            appendLine("public interface $className {")
            appendLine()
            appendLine("    @Provides")
            appendLine("    @ElementsIntoSet")
            appendLine("    @Suppress(\"UNCHECKED_CAST\")")
            appendLine("    public fun $methodName(): Set<NavKeyEntry> = setOf(")
            navKeys.forEach { key ->
                val name = key.simpleName.asString()
                appendLine("        ($name::class as KClass<NavKey>) to ($name.serializer() as KSerializer<NavKey>),")
            }
            appendLine("    )")
            appendLine("}")
        }

        try {
            val file = codeGenerator.createNewFile(
                Dependencies(aggregating = false, *navKeys.mapNotNull { it.containingFile }.toTypedArray()),
                packageName = diPackage,
                fileName = className
            )
            file.bufferedWriter().use { writer ->
                writer.write(fileSpec)
            }
        } catch (e: Exception) {
            logger.error("Failed to generate NavKey module: ${e.message}")
        }
    }

    private fun processNavigationEntries(resolver: Resolver) {
        val symbols = resolver.getSymbolsWithAnnotation("com.sorrowblue.comicviewer.framework.ui.navigation3.NavigationEntry")
        val functions = symbols.filterIsInstance<KSFunctionDeclaration>().toList()
        if (functions.isEmpty()) return

        for (function in functions) {
            val functionName = function.simpleName.asString()
            val packageName = function.packageName.asString()
            val className = functionName.replaceFirstChar(Char::titlecase)

            if (function.modifiers.contains(Modifier.PRIVATE)) {
                logger.error(
                    "Function annotated with @NavigationEntry must not be private. Please change it to internal or public.",
                    function
                )
                continue
            }

            val fileSpec = buildString {
                appendLine("/*")
                appendLine(" * Generated by NavKeyProcessor. Do not modify.")
                appendLine(" */")
                appendLine()
                appendLine("package $packageName")
                appendLine()
                appendLine("import androidx.navigation3.runtime.EntryProviderScope")
                appendLine("import androidx.navigation3.runtime.NavKey")
                appendLine("import com.sorrowblue.comicviewer.framework.ui.navigation.Navigator")
                appendLine("import com.sorrowblue.comicviewer.framework.ui.navigation3.NavigationEntryProvider")
                appendLine("import dev.zacsweers.metro.AppScope")
                appendLine("import dev.zacsweers.metro.ContributesIntoSet")
                appendLine()
                appendLine("@ContributesIntoSet(AppScope::class)")
                appendLine("internal class $className : NavigationEntryProvider {")
                appendLine()
                appendLine("    context(scope: EntryProviderScope<NavKey>)")
                appendLine("    override fun invoke(navigator: Navigator) {")
                appendLine("        $functionName(navigator)")
                appendLine("    }")
                appendLine("}")
            }

            try {
                val file = codeGenerator.createNewFile(
                    Dependencies(aggregating = false, function.containingFile!!),
                    packageName = packageName,
                    fileName = className
                )
                file.bufferedWriter().use { writer ->
                    writer.write(fileSpec)
                }
            } catch (e: Exception) {
                logger.error("Failed to generate NavigationEntryProvider for $functionName: ${e.message}")
            }
        }
    }

    private fun KSClassDeclaration.implementsNavKey(): Boolean {
        for (superType in superTypes) {
            val resolved = try {
                superType.resolve()
            } catch (e: Exception) {
                null
            } ?: continue
            val decl = resolved.declaration as? KSClassDeclaration ?: continue
            val qualifiedName = decl.qualifiedName?.asString()
            if (qualifiedName == "androidx.navigation3.runtime.NavKey" ||
                qualifiedName == "com.sorrowblue.comicviewer.framework.ui.navigation.NavigationKey"
            ) {
                return true
            }
            if (decl.implementsNavKey()) {
                return true
            }
        }
        return false
    }
}

class NavKeyProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return NavKeyProcessor(environment.codeGenerator, environment.logger)
    }
}
