name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    label: ':sparkles: feature'
  - title: '🐛 Bug Fixes'
    label: ':bug: bug'
  - title: '♻️ Refactoring'
    label: ':recycle: refactor'
  - title: '🧰 Maintenance'
    label: ':truck: chore'
  - title: '📝 Documentation'
    label: ':memo: documentation'
  - title: '⛓️ Dependency update'
    label: ':dependabot: dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: ':sparkles: feature'
    branch:
      - '/^feature[/].+/'
  - label: ':bug: bug'
    branch:
      - '/^fix[/].+/'
  - label: ':truck: chore'
    branch:
      - '/^chore[/-].+/'
  - label: ':recycle: refactor'
    branch:
      - '/^refactor[/-].+/'
  - label: ':memo: documentation'
    branch:
      - '/^doc[/-].+/'
    files:
      - '*.md'
  - label: ':dependabot: dependencies'
    branch:
      - '/dependencies[/-].+/'
      - '/renovate[/-].+/'
  - label: 'gradle'
    files:
      - 'gradle/**/*'
      - '*gradle.kts'
  - label: github
    files:
      - '.github/**/*'

prerelease: true
include-pre-releases: true

prerelease-identifier: 'beta'
