
categories:
  - title: '🚀 Features'
    label: ':sparkles: enhancement'
  - title: '🐛 Bug Fixes'
    label: ':bug: bug'
  - title: '♻️ Refactoring'
    label: ':recycle: refactor'
  - title: '🧰 Maintenance'
    labels:
      - ':truck: chore'
      - 'github'
  - title: '📝 Documentation'
    label: ':memo:documentation'
  - title: '⛓️ Dependency update'
    label: ':dependabot: dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  ## Changes
  $CHANGES

autolabeler:
  - label: ':bug: bug'
    branch:
      # fix/xxxxxxxxx
      - '/^fix[/].+/'

  - label: ':sparkles: enhancement'
    branch:
      # feature/xxxxxxxxx
      - '/^feature[/].+/'

  - label: ':truck: chore'
    branch:
      # chore/xxxxxxxxx
      - '/^chore[/-].+/'

  - label: ':recycle: refactor'
    branch:
      # refactor/xxxxxxxxxx
      - '/^refactor[/-].+/'

  - label: ':memo:documentation'
    branch:
      - '/^doc[/-].+/'
    files:
      - '*.md'

  - label: github
    files:
      - '.github/**/*'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
