name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '✨ Features'
    when:
      labels:
        - 'type: :sparkles:feature'
  - title: '🚀 Enhancements'
    when:
      labels:
        - 'type: :rocket:enhancement'
  - title: '🐛 Bug Fixes'
    when:
      labels:
        - 'type: :bug:bug'
  - title: '♻️ Refactoring'
    when:
      labels:
        - 'type: :recycle:refactor'
  - title: '⚙️ Maintenance'
    when:
      labels:
        - 'type: :gear:chore'
  - title: '📝 Documentation'
    when:
      labels:
        - 'type: :memo:documentation'
  - title: '📦 Dependency update'
    when:
      labels:
        - 'type: :dependabot:dependencies'
  - type: 'version-resolver'
    semver-increment: 'major'
    when:
      labels:
        - 'major'
  - type: 'version-resolver'
    semver-increment: 'minor'
    when:
      labels:
        - 'minor'
  - type: 'version-resolver'
    semver-increment: 'patch'
    when:
      labels:
        - 'patch'
  - type: 'version-resolver'
    semver-increment: 'patch'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: 'type: :sparkles:feature'
    branch:
      - '/^feature[/].+/'
  - label: 'type: :rocket:enhancement'
    branch:
      - '/^enhancement[/].+/'
  - label: 'type: :recycle:refactor'
    branch:
      - '/^refactor[/-].+/'
  - label: 'type: :bug:bug'
    branch:
      - '/^fix[/].+/'
  - label: 'type: :memo:documentation'
    branch:
      - '/^doc[/-].+/'
    files:
      - '*.md'
  - label: 'type: :dependabot:dependencies'
    branch:
      - '/dependencies[/-].+/'
      - '/renovate[/-].+/'
  - label: 'type: :gear:chore'
    branch:
      - '/^chore[/-].+/'

prerelease: true

include-pre-releases: true

prerelease-identifier: 'beta'
