/*
 * Copyright 2026 SorrowBlue. See LICENSE for details.
 */

package com.sorrowblue.comicviewer.framework.navigation.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.KSValueParameter
import com.google.devtools.ksp.symbol.Modifier

internal class NavKeyProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        processNavKeys(resolver)
        processNavigationEntries(resolver)
        return emptyList()
    }

    private fun processNavKeys(resolver: Resolver) {
        val symbols = resolver.getSymbolsWithAnnotation("kotlinx.serialization.Serializable")

        val navKeys = symbols
            .filterIsInstance<KSClassDeclaration>()
            .filter { it.implementsNavKey() }
            .toList()

        if (navKeys.isEmpty()) return

        val fileInfoNavKeys = navKeys.filter { it.implementsFileInfoNavKey() }
        val hasFileInfoNavKeys = fileInfoNavKeys.isNotEmpty()

        val firstKey = navKeys.first()
        val keyPackage = firstKey.packageName.asString()
        val diPackage = if (keyPackage.endsWith(".navigation")) {
            keyPackage.substringBeforeLast(".navigation") + ".di"
        } else if (keyPackage.endsWith(".navigation3")) {
            keyPackage.substringBeforeLast(".navigation3") + ".di"
        } else {
            "$keyPackage.di"
        }

        val prefix = "com.sorrowblue.comicviewer."
        val moduleName = if (keyPackage.startsWith(prefix)) {
            keyPackage.removePrefix(prefix)
                .replace(".", "_")
                .split("_")
                .filter { it != "navigation" && it != "navigation3" && it != "feature" && it != "di" }
                .joinToString("") { it.replaceFirstChar(Char::titlecase) }
        } else {
            keyPackage.replace(".", "_")
                .split("_")
                .joinToString("") { it.replaceFirstChar(Char::titlecase) }
        }

        val className = "Generated${moduleName}NavKeyModule"
        val methodName = "provide${moduleName}NavKeySubclassMap"
        val fileInfoMethodName = "provide${moduleName}FileInfoNavKeySubclassMap"

        val fileSpec = buildString {
            appendLine("/*")
            appendLine(" * Generated by NavKeyProcessor. Do not modify.")
            appendLine(" */")
            appendLine()
            appendLine("package $diPackage")
            appendLine()
            navKeys.forEach { key ->
                appendLine("import ${key.qualifiedName?.asString()}")
            }
            appendLine("import androidx.navigation3.runtime.NavKey")
            if (hasFileInfoNavKeys) {
                appendLine("import com.sorrowblue.comicviewer.feature.file.nav.FileInfoNavKey")
            }
            appendLine("import com.sorrowblue.comicviewer.framework.navigation.NavKeyEntry")
            appendLine("import dev.zacsweers.metro.AppScope")
            appendLine("import dev.zacsweers.metro.BindingContainer")
            appendLine("import dev.zacsweers.metro.ContributesTo")
            appendLine("import dev.zacsweers.metro.ElementsIntoSet")
            appendLine("import dev.zacsweers.metro.Provides")
            appendLine("import kotlin.reflect.KClass")
            appendLine("import kotlinx.serialization.KSerializer")
            appendLine()
            appendLine("@ContributesTo(AppScope::class)")
            appendLine("@BindingContainer")
            appendLine("public object $className {")
            appendLine()
            appendLine("    @Provides")
            appendLine("    @ElementsIntoSet")
            appendLine("    @Suppress(\"UNCHECKED_CAST\")")
            appendLine("    public fun $methodName(): Set<NavKeyEntry> = setOf(")
            navKeys.forEach { key ->
                val name = key.simpleName.asString()
                appendLine("        ($name::class as KClass<NavKey>) to ($name.serializer() as KSerializer<NavKey>),")
            }
            appendLine("    )")
            if (hasFileInfoNavKeys) {
                appendLine()
                appendLine("    @Provides")
                appendLine("    @ElementsIntoSet")
                appendLine("    public fun $fileInfoMethodName(): Set<KClass<out FileInfoNavKey>> = setOf(")
                fileInfoNavKeys.forEach { key ->
                    val name = key.simpleName.asString()
                    appendLine("        $name::class,")
                }
                appendLine("    )")
            }
            appendLine("}")
        }

        try {
            val file = codeGenerator.createNewFile(
                Dependencies(aggregating = false, *navKeys.mapNotNull { it.containingFile }.toTypedArray()),
                packageName = diPackage,
                fileName = className
            )
            file.bufferedWriter().use { writer ->
                writer.write(fileSpec)
            }
        } catch (e: Exception) {
            logger.error("Failed to generate NavKey module: ${e.message}")
        }
    }

    private fun processNavigationEntries(resolver: Resolver) {
        val symbols = resolver.getSymbolsWithAnnotation("com.sorrowblue.comicviewer.framework.navigation.NavigationEntry")
        val functions = symbols.filterIsInstance<KSFunctionDeclaration>().toList()
        if (functions.isEmpty()) return

        for (function in functions) {
            val functionName = function.simpleName.asString()
            val packageName = function.packageName.asString()
            val className = functionName.replaceFirstChar(Char::titlecase)

            if (function.modifiers.contains(Modifier.PRIVATE)) {
                logger.error(
                    "Function annotated with @NavigationEntry must not be private. Please change it to internal or public.",
                    function
                )
                continue
            }

            val diParams = function.parameters.filterNot { isNavigator(it) }
            val hasDiParams = diParams.isNotEmpty()

            val imports = sortedSetOf(
                "androidx.navigation3.runtime.EntryProviderScope",
                "androidx.navigation3.runtime.NavKey",
                "com.sorrowblue.comicviewer.framework.navigation.NavigationEntryProvider",
                "com.sorrowblue.comicviewer.framework.navigation.Navigator",
                "dev.zacsweers.metro.AppScope",
                "dev.zacsweers.metro.ContributesIntoSet",
            )
            if (hasDiParams) {
                imports.add("dev.zacsweers.metro.Inject")
                diParams.forEach { param ->
                    param.type.resolve().collectImports(imports, packageName)
                }
            }

            val fileSpec = buildString {
                appendLine("/*")
                appendLine(" * Generated by NavKeyProcessor. Do not modify.")
                appendLine(" */")
                appendLine()
                appendLine("package $packageName")
                appendLine()
                imports.forEach { imp ->
                    appendLine("import $imp")
                }
                appendLine()
                if (hasDiParams) {
                    appendLine("@Inject")
                }
                appendLine("@ContributesIntoSet(AppScope::class)")
                if (hasDiParams) {
                    appendLine("internal class $className(")
                    diParams.forEach { param ->
                        val paramName = param.name!!.asString()
                        val typeName = param.type.resolve().toSimpleTypeName()
                        appendLine("    private val $paramName: $typeName,")
                    }
                    appendLine(") : NavigationEntryProvider {")
                } else {
                    appendLine("internal class $className : NavigationEntryProvider {")
                }
                appendLine()
                appendLine("    context(scope: EntryProviderScope<NavKey>)")
                appendLine("    override fun invoke(navigator: Navigator) {")
                val callArgs = function.parameters.joinToString(", ") { param ->
                    if (isNavigator(param)) "navigator" else param.name!!.asString()
                }
                appendLine("        $functionName($callArgs)")
                appendLine("    }")
                appendLine("}")
            }

            try {
                val file = codeGenerator.createNewFile(
                    Dependencies(aggregating = false, function.containingFile!!),
                    packageName = packageName,
                    fileName = className
                )
                file.bufferedWriter().use { writer ->
                    writer.write(fileSpec)
                }
            } catch (e: Exception) {
                logger.error("Failed to generate NavigationEntryProvider for $functionName: ${e.message}")
            }
        }
    }

    private fun isNavigator(param: KSValueParameter): Boolean {
        val type = param.type.resolve()
        val qName = type.declaration.qualifiedName?.asString()
        return qName == "com.sorrowblue.comicviewer.framework.navigation.Navigator"
    }

    private fun KSType.collectImports(imports: MutableSet<String>, currentPackage: String) {
        val qName = declaration.qualifiedName?.asString()
        if (qName != null && !qName.startsWith("kotlin.")) {
            val pkg = declaration.packageName.asString()
            if (pkg != currentPackage) {
                imports.add(qName)
            }
        }
        arguments.forEach { arg ->
            arg.type?.resolve()?.collectImports(imports, currentPackage)
        }
    }

    private fun KSType.toSimpleTypeName(): String {
        val simpleName = declaration.simpleName.asString()
        val typeArgs = arguments
        val typeArgsString = if (typeArgs.isNotEmpty()) {
            "<" + typeArgs.joinToString(", ") { arg ->
                arg.type?.resolve()?.toSimpleTypeName() ?: "*"
            } + ">"
        } else {
            ""
        }
        val nullableSuffix = if (isMarkedNullable) "?" else ""
        return "$simpleName$typeArgsString$nullableSuffix"
    }

    private fun KSClassDeclaration.implementsNavKey(
        visited: MutableSet<KSClassDeclaration> = mutableSetOf(),
    ): Boolean {
        if (!visited.add(this)) return false
        for (superType in superTypes) {
            val resolved = try {
                superType.resolve()
            } catch (e: Exception) {
                null
            } ?: continue
            val decl = resolved.declaration as? KSClassDeclaration ?: continue
            val qualifiedName = decl.qualifiedName?.asString()
            if (qualifiedName == "androidx.navigation3.runtime.NavKey" ||
                qualifiedName == "com.sorrowblue.comicviewer.framework.navigation.NavigationKey"
            ) {
                return true
            }
            if (decl.implementsNavKey(visited)) {
                return true
            }
        }
        return false
    }

    private fun KSClassDeclaration.implementsFileInfoNavKey(
        visited: MutableSet<KSClassDeclaration> = mutableSetOf(),
    ): Boolean {
        if (!visited.add(this)) return false
        for (superType in superTypes) {
            val resolved = try {
                superType.resolve()
            } catch (e: Exception) {
                null
            } ?: continue
            val decl = resolved.declaration as? KSClassDeclaration ?: continue
            val qualifiedName = decl.qualifiedName?.asString()
            if (qualifiedName == "com.sorrowblue.comicviewer.feature.file.nav.FileInfoNavKey") {
                return true
            }
            if (decl.implementsFileInfoNavKey(visited)) {
                return true
            }
        }
        return false
    }
}

internal class NavKeyProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return NavKeyProcessor(environment.codeGenerator, environment.logger)
    }
}
