name: Setup Java and Gradle
runs:
  using: "composite"
  steps:
    - name: Setup JDK 21
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Run chmod to make gradlew executable
      shell: bash
      run: chmod +x ./gradlew
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
