include required("conveyor.conf")

app {
  windows.store {
    identity-name = ${?MS_STORE_IDENTITY_NAME}
    publisher = ${?MS_STORE_PUBLISHER}
    publisher-display-name = ${?MS_STORE_PUBLISHER_DISPLAY_NAME}
    store-id = ${?MS_STORE_APP_ID}
    client-id = ${?MS_STORE_CLIENT_ID}
    client-secret = ${?MS_STORE_CLIENT_SECRET}
    tenant-id = ${?MS_STORE_TENANT_ID}
  }
}
