include "#!../../gradlew -p ../../ -q app:jvmApp:printConveyorConfig"
include required("https://raw.githubusercontent.com/hydraulic-software/conveyor/master/configs/jvm/extract-native-libraries.conf")

app {
  machines = [linux, mac, windows]

  display-name = "MultiComicViewer"

  rdns-name = "com.sorrowblue.comicviewer"

  icons = "../../docs/images/icon.svg"

  compression-level = low

  license = "Apache-2.0"
  vcs-url = "https://github.com/SorrowBlue/ComicViewer"
  site.consistency-checks = warn

  site {
    include required("extra-header.conf")
  }

  skiko-version = "0.150.1"
  maven-repo = "https://repo1.maven.org/maven2"

  linux {
    aarch64.inputs += ${app.maven-repo}"/org/jetbrains/skiko/skiko-awt-runtime-linux-arm64/"${app.skiko-version}"/skiko-awt-runtime-linux-arm64-"${app.skiko-version}".jar"
    amd64.inputs += ${app.maven-repo}"/org/jetbrains/skiko/skiko-awt-runtime-linux-x64/"${app.skiko-version}"/skiko-awt-runtime-linux-x64-"${app.skiko-version}".jar"
  }
  mac {
    check-binary-versions = false
    aarch64.inputs += ${app.maven-repo}"/org/jetbrains/skiko/skiko-awt-runtime-macos-arm64/"${app.skiko-version}"/skiko-awt-runtime-macos-arm64-"${app.skiko-version}".jar"
    amd64.inputs += ${app.maven-repo}"/org/jetbrains/skiko/skiko-awt-runtime-macos-x64/"${app.skiko-version}"/skiko-awt-runtime-macos-x64-"${app.skiko-version}".jar"
  }
  windows {
    aarch64.inputs += ${app.maven-repo}"/org/jetbrains/skiko/skiko-awt-runtime-windows-arm64/"${app.skiko-version}"/skiko-awt-runtime-windows-arm64-"${app.skiko-version}".jar"
    amd64.inputs += ${app.maven-repo}"/org/jetbrains/skiko/skiko-awt-runtime-windows-x64/"${app.skiko-version}"/skiko-awt-runtime-windows-x64-"${app.skiko-version}".jar"
  }
}

conveyor.compatibility-level = 22
