title: ComicViewer
description: Manga/e-book/image viewer compatible with Material You.
show_downloads: true
theme: jekyll-theme-cayman
include:
  - .well-known
  - dokka
keep_files:
  - .well-known
  - dokka
