name: Build

on:
  workflow_call:

jobs:

  android-build:
    uses: SorrowBlue/github-actions/.github/workflows/android-build.yml@main
    secrets: inherit
    with:
      environment: android
      task: bundlePrerelease assemblePrerelease
      output-path: app/android/build/outputs/

  build-jvm:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Ubuntu
          - os: windows-latest
            name: Windows
          - os: macos-latest
            name: Mac
    uses: SorrowBlue/github-actions/.github/workflows/jvm-build.yml@main
    with:
      runs-on: ${{ matrix.os }}
      name: ${{ matrix.name }}
      task: packageDistributionForCurrentOS
      output-name: jvm-${{ matrix.name }}
      output-path: app/jvm/build/compose/binaries/main/
