name: Build
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    secrets:
      ANDROID_STORE_FILE_BASE64:
        required: true
      ANDROID_STORE_PASSWORD:
        required: true
      ANDROID_KEY_ALIAS:
        required: true
      ANDROID_KEY_PASSWORD:
        required: true

jobs:

  build-android:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Decode android keystore file
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: 'android_keystore.jks'
          encodedString: ${{ secrets.ANDROID_STORE_FILE_BASE64 }}
      - name: Run bundleRelease
        run: ./gradlew bundlePrerelease assemblePrerelease
        env:
          ORG_GRADLE_PROJECT_androidSigningReleaseStoreFile: ${{ steps.android_keystore.outputs.filePath }}
          ORG_GRADLE_PROJECT_androidSigningReleaseStorePassword: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_androidSigningReleaseKeyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_androidSigningReleaseKeyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: android
          path: composeApp/build/outputs/

  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Set artifact name
        id: set_artifact_name
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            $ARTIFACT_NAME="desktop-${{ matrix.os }}".Replace("-latest", "")
            [System.IO.File]::WriteAllText("$env:GITHUB_ENV", "artifact_name=$ARTIFACT_NAME`n")
          else
            ARTIFACT_NAME="desktop-${{ matrix.os }}"
            ARTIFACT_NAME=${ARTIFACT_NAME/-latest/}
            echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_ENV
          fi
      - name: Run packageDistributionForCurrentOS
        run: ./gradlew packageDistributionForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: composeApp/build/compose/binaries/main/

  build:
    name: All Build Passed
    runs-on: ubuntu-latest
    needs: [build-android, build-desktop]
    steps:
      - name : Confirm All Build Jobs Succeeded
        run: echo "✅ All build jobs (Android, Windows, macOS, Linux) completed successfully."
