name: 'Build Desktop'
on:
  workflow_call:

jobs:
  build-desktop:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    environment: android
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Run packageDistributionForCurrentOS
        run: ./gradlew packageDistributionForCurrentOS
      - name: Upload Desktop Binaries
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ runner.os }}
          path: composeApp/build/compose/binaries/main/
