name: Build
on:
  workflow_call:

jobs:

  android-build:
    uses: SorrowBlue/github-actions/.github/workflows/android-build.yml@main
    secrets: inherit
    with:
      environment: android
      task: bundlePrerelease assemblePrerelease
      output-path: app/android/build/outputs/

  build-jvm:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    uses: SorrowBlue/github-actions/.github/workflows/jvm-build.yml@main
    with:
      runs-on: ${{ matrix.os }}
      task: packageDistributionForCurrentOS
      output-path: app/jvm/build/compose/binaries/main/
