name: Build
on:
  workflow_call:

jobs:

  android-build:
    uses: SorrowBlue/github-actions/.github/workflows/android-build.yml@main
    secrets: inherit
    with:
      environment: android
      task: bundlePrerelease assemblePrerelease
      output-path: app/android/build/outputs/

#  build-jvm:
#    strategy:
#      matrix:
#        os: [ ubuntu-latest, windows-latest, macos-latest ]
#    runs-on: ${{ matrix.os }}
#    environment: android
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v6
#      - name: Setup JDK and Gradle
#        uses: ./.github/actions/setup-java-gradle
#      - name: Run packageDistributionForCurrentOS
#        run: ./gradlew packageDistributionForCurrentOS
#      - name: Upload Jvm Binaries
#        uses: actions/upload-artifact@v7
#        with:
#          name: jvm-${{ runner.os }}
#          path: app/jvm/build/compose/binaries/main/
#
#  build:
#    name: All Build Passed
#    runs-on: ubuntu-latest
#    environment: android
#    needs: [ build-android, build-jvm ]
#    steps:
#      - name: Confirm All Build Jobs Succeeded
#        run: echo "✅ All build jobs (Android, Windows, macOS, Linux) completed successfully."

