name: 'Build Desktop'
on:
  workflow_call:

jobs:
  build-desktop:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    environment: android
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Set artifact name
        id: set_artifact_name
        run: |
          ARTIFACT_NAME="desktop-${{ runner.os }}"
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_ENV
      - name: Run packageDistributionForCurrentOS
        run: ./gradlew packageDistributionForCurrentOS
      - name: Upload Desktop Binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: composeApp/build/compose/binaries/main/
