name: Cache Clear

on: workflow_dispatch

jobs:
  clear:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Delete Branch Cache
        run: gh cache delete --all --ref "${{ github.ref }}" --succeed-on-no-caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
