name: Detekt & Lint & Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: lint
        run: ./gradlew app:lintRelease
        env:
          BOX_CLIENT_ID: ${{ secrets.BOX_CLIENT_ID }}
          BOX_CLIENT_SECRET: ${{ secrets.BOX_CLIENT_SECRET }}
          DROP_BOX_API_KEY: ${{ secrets.DROP_BOX_API_KEY }}

      - name: reviewdog report
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat ./build/reports/lint/lint-result.sarif |
          reviewdog -f="sarif" -name="android-lint" -reporter="github-pr-review" -filter-mode="nofilter"

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: detekt
        run: ./gradlew detektRelease
        env:
          BOX_CLIENT_ID: ${{ secrets.BOX_CLIENT_ID }}
          BOX_CLIENT_SECRET: ${{ secrets.BOX_CLIENT_SECRET }}
          DROP_BOX_API_KEY: ${{ secrets.DROP_BOX_API_KEY }}
      - name: reviewdog report
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat ./build/reports/detekt/merge.sarif |
          reviewdog -f="sarif" -name="detekt" -reporter="github-pr-review" -filter-mode="nofilter"

  build:
    runs-on: ubuntu-latest
    environment: android
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle

      - name: Decode android keystore file
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: 'android_keystore.jks'
          encodedString: ${{ secrets.ANDROID_STORE_FILE_BASE64 }}

      - name: assemble
        run: ./gradlew bundleRelease
        env:
          release_storeFile: ${{ steps.android_keystore.outputs.filePath }}
          release_storePassword: ${{ secrets.ANDROID_STORE_PASSWORD }}
          release_keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          release_keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          BOX_CLIENT_ID: ${{ secrets.BOX_CLIENT_ID }}
          BOX_CLIENT_SECRET: ${{ secrets.BOX_CLIENT_SECRET }}
          DROP_BOX_API_KEY: ${{ secrets.DROP_BOX_API_KEY }}
