name: Detekt & Lint & Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  # required for all workflows
  security-events: write

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Run app:lintRelease
        run: ./gradlew app:lintRelease

  detekt_build-logic_detektMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Run :build-logic:detektMain
        run: ./gradlew :build-logic:detektMain
      - uses: github/codeql-action/upload-sarif@v3
        if: ${{ !cancelled() }}
        with:
          sarif_file: build-logic/build/reports/detekt/main.sarif

  detekt_detektRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Run detektRelease
        run: ./gradlew detektRelease
      - uses: github/codeql-action/upload-sarif@v3
        if: ${{ !cancelled() }}
        with:
          sarif_file: build/reports/detekt/merge.sarif

  detekt_detektAndroidRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Run detektAndroidRelease
        run: ./gradlew detektAndroidRelease
      - uses: github/codeql-action/upload-sarif@v3
        if: ${{ !cancelled() }}
        with:
          sarif_file: build/reports/detekt/merge.sarif

  detekt_detektJvmMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Run detektJvmMain
        run: ./gradlew detektJvmMain
      - uses: github/codeql-action/upload-sarif@v3
        if: ${{ !cancelled() }}
        with:
          sarif_file: build/reports/detekt/merge.sarif

  detekt_detektMetadataCommonMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Run detektMetadataCommonMain
        run: ./gradlew detektMetadataCommonMain
      - uses: github/codeql-action/upload-sarif@v3
        if: ${{ !cancelled() }}
        with:
          sarif_file: build/reports/detekt/merge.sarif

  build:
    runs-on: ubuntu-latest
    environment: android
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Decode android keystore file
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: 'android_keystore.jks'
          encodedString: ${{ secrets.ANDROID_STORE_FILE_BASE64 }}
      - name: Run bundleRelease
        run: ./gradlew bundleRelease
        env:
          ORG_GRADLE_PROJECT_androidSigningReleaseStoreFile: ${{ steps.android_keystore.outputs.filePath }}
          ORG_GRADLE_PROJECT_androidSigningReleaseStorePassword: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_androidSigningReleaseKeyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_androidSigningReleaseKeyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
