name: Detekt & Lint & Build

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  # Required to upload SARIF files
  security-events: write

jobs:

  detekt:
    uses: ./.github/workflows/detekt.yml

  lint:
    uses: ./.github/workflows/lint.yml

  build-android:
    runs-on: ubuntu-latest
    needs: [detekt, lint]
    environment: android
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Decode android keystore file
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: 'android_keystore.jks'
          encodedString: ${{ secrets.ANDROID_STORE_FILE_BASE64 }}
      - name: Run bundleRelease
        run: ./gradlew bundlePrerelease assemblePrerelease
        env:
          ORG_GRADLE_PROJECT_androidSigningReleaseStoreFile: ${{ steps.android_keystore.outputs.filePath }}
          ORG_GRADLE_PROJECT_androidSigningReleaseStorePassword: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_androidSigningReleaseKeyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_androidSigningReleaseKeyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: android
          path: composeApp/build/outputs/
  build-windows:
    runs-on: windows-latest
    needs: [detekt, lint]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Run packageDistributionForCurrentOS
        run: ./gradlew packageDistributionForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: composeApp/build/compose/binaries/main/

  build-macos:
    runs-on: macos-latest
    needs: [detekt, lint]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Run packageDistributionForCurrentOS
        run: ./gradlew packageDistributionForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: macos
          path: composeApp/build/compose/binaries/main/

  build-linux:
    runs-on: ubuntu-latest
    needs: [detekt, lint]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Run packageDistributionForCurrentOS
        run: ./gradlew packageDistributionForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: composeApp/build/compose/binaries/main/
