name: Internal App Sharing

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.idea/**'
      - '.run/**'
      - 'config/**'
      - 'docs/**'
      - 'iosApp/**'

permissions:
  contents: read
  id-token: write

jobs:
  build-upload:
    uses: SorrowBlue/github-actions/.github/workflows/android-publish.yml@main
    secrets: inherit
    with:
      environment: android
      fetch-depth: 0
      task: bundleInternal
      package-name: com.sorrowblue.comicviewer
      release-files: app/android/build/outputs/bundle/internal/android-internal.aab
      tracks: internalsharing
      mapping-file: app/android/build/outputs/mapping/internal/mapping.txt
      debug-symbols: app/android/build/intermediates/merged_native_libs/internal/mergeInternalNativeLibs/out/lib

  notify:
    needs: build-upload
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: ":sparkles: Uploaded to internal app share."
          description: |
            Click [here](${{ needs.build-upload.outputs.internalSharingDownloadUrl }}) to download!
          color: 0xff91a4
