name: Upload AAB to Internal App Sharing (Workload Identity)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.idea/**'
      - '.run/**'
      - 'config/**'
      - 'docs/**'
      - 'iosApp/**'
permissions:
  contents: read
  id-token: write

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    environment: android
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Run bundleInternal
        run: ./gradlew bundleInternal
        env:
          ORG_GRADLE_PROJECT_androidSigningReleaseStoreFile: ${{ steps.android_keystore.outputs.filePath }}
          ORG_GRADLE_PROJECT_androidSigningReleaseStorePassword: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_androidSigningReleaseKeyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_androidSigningReleaseKeyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Upload AAB to Internal App Sharing (Attempt)
        id: upload
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: com.sorrowblue.comicviewer
          releaseFiles: composeApp/build/outputs/bundle/internal/composeApp-internal.aab
          track: internalsharing
          mappingFile: composeApp/build/outputs/mapping/internal/mapping.txt
          debugSymbols: composeApp/build/intermediates/merged_native_libs/internal/mergeInternalNativeLibs/out/lib

      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: ":sparkles: Uploaded to internal app share."
          description: |
            Click [here](${{ steps.upload.outputs.internalSharingDownloadUrl }}) to download!
          color: 0xff91a4
