name: Upload AAB to Internal App Sharing (Workload Identity)

on:
  push:
    branches:
      - main # またはリリース用のブランチなど

# これを追加: OIDCトークン発行権限
permissions:
  contents: read # コードのチェックアウトに必要
  id-token: write # google-github-actions/auth に必要

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-java-gradle

      - name: Build AAB
        run: ./gradlew bundleInternal

      # --- ここから Workload Identity Federation による認証 ---
      - name: Authenticate to Google Cloud
        id: auth # このステップのID (後で参照するため)
        uses: google-github-actions/auth@v2 # 最新版を確認
        with:
          # GCP設定の値を入力
          workload_identity_provider: 'projects/303610403123/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'googleplayconsole@comicviewer.iam.gserviceaccount.com' # 例: play-uploader-sa@your-project-id.iam.gserviceaccount.com

      # --- r0adkll/upload-google-play の呼び出し ---
      - name: Upload AAB to Internal App Sharing (Attempt)
        id: upload
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          # 他のパラメータは通常通り設定
          packageName: com.sorrowblue.comicviewer
          releaseFiles: composeApp/build/outputs/bundle/internal/composeApp-internal.aab
          track: internalsharing
          mappingFile: composeApp/build/outputs/mapping/internal/mapping.txt
          debugSymbols: composeApp/build/intermediates/merged_native_libs/internal/mergeInternalNativeLibs/out/lib

      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: ":sparkles: Uploaded to internal app share."
          description: |
            Click [here](${{ steps.upload.outputs.internalSharingDownloadUrl }}) to download!
          color: 0xff91a4
