name: Lint

on:
  workflow_call:

permissions:
  contents: read
  checks: write
  security-events: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: 🔍️Run analyze
        run: |
          ./gradlew :build-logic:detektMain \
                    reportMerge \
                    checkVersionCatalog \
                    app:androidApp:lintDebug \
                    app:androidApp:lintInternal \
                    app:androidApp:lintPrerelease \
                    app:androidApp:lintRelease \
                    --continue
      - name: Upload Detekt SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: ${{ !cancelled() }}
        with:
          sarif_file: "build/reports/detekt/merge.sarif"
          category: "detekt"
      - name: Upload Detekt (build-logic) SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: ${{ !cancelled() }}
        with:
          sarif_file: "build-logic/build/reports/detekt/main.sarif"
          category: "detekt-build-logic"
      - name: Upload Android Lint (Debug) SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: ${{ !cancelled() }}
        with:
          sarif_file: "app/androidApp/build/reports/lint-results-debug.sarif"
          category: "android-lint-debug"
      - name: Upload Android Lint (Internal) SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: ${{ !cancelled() }}
        with:
          sarif_file: "app/androidApp/build/reports/lint-results-internal.sarif"
          category: "android-lint-internal"
      - name: Upload Android Lint (Prerelease) SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: ${{ !cancelled() }}
        with:
          sarif_file: "app/androidApp/build/reports/lint-results-prerelease.sarif"
          category: "android-lint-prerelease"
      - name: Upload Android Lint (Release) SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: ${{ !cancelled() }}
        with:
          sarif_file: "app/androidApp/build/reports/lint-results-release.sarif"
          category: "android-lint-release"
