name: Release

on:
  workflow_dispatch:
  release:
    types: [ published ]

permissions:
  contents: read
  # required for all workflows
  security-events: write

jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check last workflow run status on main
        uses: actions/github-script@v7
        with:
          script: |
            const workflow_id = 'lint-test-build.yml';
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow_id,
              branch: 'main',
              per_page: 1,
              enable_debug_logging: true
            });
            const latest = runs.data.workflow_runs[0];
            core.info(runs.data.total_count)
            core.info(latest.html_url)
            core.info(latest.conclusion)
            if (!latest || latest.conclusion !== 'success') {
              core.setFailed('Latest workflow run on main is not successful.');
            }
