name: Sync Labels

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'

jobs:
  sync-labels:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install -g github-label-sync
      - name: Run github-label-sync
        run: github-label-sync --access-token ${{ secrets.GITHUB_TOKEN }} --labels .github/labels.yml ${{ github.repository }}
