name: Windows Publish (Shared)

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
        description: "Release channel (test-flight or production)"

jobs:
  jvm-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Run jvmJar
        run: ./gradlew :app:jvmApp:jvmJar :app:jvmApp:printConveyorConfig :app:jvmApp:writeConveyorConfig :app:jvmApp:copyConveyorInputs
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: build-windows-latest
          path: app/jvmApp/build/all-libs

  release-ms-store:
    name: Release to Microsoft Store
    needs: jvm-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-java-gradle

      - name: Download Windows build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: build-windows-latest
          path: ./artifacts/windows
      - name: Run printConveyorConfig
        run: ./gradlew -q printConveyorConfig

      # Test Flight
      - name: Build MSIX Package for Test Flight
        if: inputs.channel == 'test-flight'
        uses: hydraulic-software/conveyor/actions/build@5011cc412f9c3a67d8f72f9ea5db5f34c4a68e36 # v22.1
        with:
          command: -f config/conveyor/ci.conveyor.conf -K='app.machines=[windows.amd64]' make windows-msix
          signing_key: ${{ secrets.CONVEYOR_SIGNING_KEY }}
          agree_to_license: 1
        env:
          MS_STORE_IDENTITY_NAME: ${{ secrets.MS_STORE_IDENTITY_NAME }}
          MS_STORE_PUBLISHER: ${{ secrets.MS_STORE_PUBLISHER }}
          MS_STORE_PUBLISHER_DISPLAY_NAME: ${{ secrets.MS_STORE_PUBLISHER_DISPLAY_NAME }}
          MS_STORE_APP_ID: ${{ secrets.MS_STORE_APP_ID }}

      - name: Setup MSStore CLI
        if: inputs.channel == 'test-flight'
        uses: microsoft/microsoft-store-apppublisher@cc9910a8d59f2eb55cbb83df0a3800cf3b5300e0 # v1.4

      - name: Upload MSIX to Microsoft Store Test Flight
        if: inputs.channel == 'test-flight'
        run: |
          msstore reconfigure --tenantId ${{ secrets.MS_STORE_TENANT_ID }} --clientId ${{ secrets.MS_STORE_CLIENT_ID }} --clientSecret ${{ secrets.MS_STORE_CLIENT_SECRET }}
          msstore publish output/*.msix -id ${{ secrets.MS_STORE_APP_ID }} --flightId ${{ secrets.MS_STORE_TEST_FLIGHT_ID }}

      # Production
      - name: Run Conveyor to release to Microsoft Store (Production)
        if: inputs.channel == 'production'
        uses: hydraulic-software/conveyor/actions/build@5011cc412f9c3a67d8f72f9ea5db5f34c4a68e36 # v22.1
        with:
          command: -f config/conveyor/ci.conveyor.conf -K='app.machines=[windows.amd64]' make ms-store-release
          signing_key: ${{ secrets.CONVEYOR_SIGNING_KEY }}
          agree_to_license: 1
        env:
          MS_STORE_CLIENT_ID: ${{ secrets.MS_STORE_CLIENT_ID }}
          MS_STORE_CLIENT_SECRET: ${{ secrets.MS_STORE_CLIENT_SECRET }}
          MS_STORE_TENANT_ID: ${{ secrets.MS_STORE_TENANT_ID }}
          MS_STORE_APP_ID: ${{ secrets.MS_STORE_APP_ID }}
          MS_STORE_IDENTITY_NAME: ${{ secrets.MS_STORE_IDENTITY_NAME }}
          MS_STORE_PUBLISHER: ${{ secrets.MS_STORE_PUBLISHER }}
          MS_STORE_PUBLISHER_DISPLAY_NAME: ${{ secrets.MS_STORE_PUBLISHER_DISPLAY_NAME }}

      - name: Upload conveyor artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: conveyor-output
          path: output/*
